function getLanguages() {
    return [
        { code: 'auto', name: chrome.i18n.getMessage('autoDetect') || 'Detect Language' },
        { code: 'af', name: chrome.i18n.getMessage('langAfrikaans') || 'Afrikaans' },
        { code: 'sq', name: chrome.i18n.getMessage('langAlbanian') || 'Albanian' },
        { code: 'ar', name: chrome.i18n.getMessage('langArabic') || 'Arabic' },
        { code: 'hy', name: chrome.i18n.getMessage('langArmenian') || 'Armenian' },
        { code: 'az', name: chrome.i18n.getMessage('langAzerbaijani') || 'Azerbaijani' },
        { code: 'eu', name: chrome.i18n.getMessage('langBasque') || 'Basque' },
        { code: 'be', name: chrome.i18n.getMessage('langBelarusian') || 'Belarusian' },
        { code: 'bn', name: chrome.i18n.getMessage('langBengali') || 'Bengali' },
        { code: 'bs', name: chrome.i18n.getMessage('langBosnian') || 'Bosnian' },
        { code: 'bg', name: chrome.i18n.getMessage('langBulgarian') || 'Bulgarian' },
        { code: 'ca', name: chrome.i18n.getMessage('langCatalan') || 'Catalan' },
        { code: 'ceb', name: chrome.i18n.getMessage('langCebuano') || 'Cebuano' },
        { code: 'zh-CN', name: chrome.i18n.getMessage('langChineseSimp') || 'Chinese (Simplified)' },
        { code: 'zh-TW', name: chrome.i18n.getMessage('langChineseTrad') || 'Chinese (Traditional)' },
        { code: 'hr', name: chrome.i18n.getMessage('langCroatian') || 'Croatian' },
        { code: 'cs', name: chrome.i18n.getMessage('langCzech') || 'Czech' },
        { code: 'da', name: chrome.i18n.getMessage('langDanish') || 'Danish' },
        { code: 'nl', name: chrome.i18n.getMessage('langDutch') || 'Dutch' },
        { code: 'en', name: chrome.i18n.getMessage('langEnglish') || 'English' },
        { code: 'eo', name: chrome.i18n.getMessage('langEsperanto') || 'Esperanto' },
        { code: 'et', name: chrome.i18n.getMessage('langEstonian') || 'Estonian' },
        { code: 'fi', name: chrome.i18n.getMessage('langFinnish') || 'Finnish' },
        { code: 'fr', name: chrome.i18n.getMessage('langFrench') || 'French' },
        { code: 'gl', name: chrome.i18n.getMessage('langGalician') || 'Galician' },
        { code: 'ka', name: chrome.i18n.getMessage('langGeorgian') || 'Georgian' },
        { code: 'de', name: chrome.i18n.getMessage('langGerman') || 'German' },
        { code: 'el', name: chrome.i18n.getMessage('langGreek') || 'Greek' },
        { code: 'gu', name: chrome.i18n.getMessage('langGujarati') || 'Gujarati' },
        { code: 'ht', name: chrome.i18n.getMessage('langHaitianCreole') || 'Haitian Creole' },
        { code: 'ha', name: chrome.i18n.getMessage('langHausa') || 'Hausa' },
        { code: 'haw', name: chrome.i18n.getMessage('langHawaiian') || 'Hawaiian' },
        { code: 'he', name: chrome.i18n.getMessage('langHebrew') || 'Hebrew' },
        { code: 'hi', name: chrome.i18n.getMessage('langHindi') || 'Hindi' },
        { code: 'hmn', name: chrome.i18n.getMessage('langHmong') || 'Hmong' },
        { code: 'hu', name: chrome.i18n.getMessage('langHungarian') || 'Hungarian' },
        { code: 'is', name: chrome.i18n.getMessage('langIcelandic') || 'Icelandic' },
        { code: 'ig', name: chrome.i18n.getMessage('langIgbo') || 'Igbo' },
        { code: 'id', name: chrome.i18n.getMessage('langIndonesian') || 'Indonesian' },
        { code: 'ga', name: chrome.i18n.getMessage('langIrish') || 'Irish' },
        { code: 'it', name: chrome.i18n.getMessage('langItalian') || 'Italian' },
        { code: 'ja', name: chrome.i18n.getMessage('langJapanese') || 'Japanese' },
        { code: 'jv', name: chrome.i18n.getMessage('langJavanese') || 'Javanese' },
        { code: 'kn', name: chrome.i18n.getMessage('langKannada') || 'Kannada' },
        { code: 'kk', name: chrome.i18n.getMessage('langKazakh') || 'Kazakh' },
        { code: 'km', name: chrome.i18n.getMessage('langKhmer') || 'Khmer' },
        { code: 'ko', name: chrome.i18n.getMessage('langKorean') || 'Korean' },
        { code: 'ku', name: chrome.i18n.getMessage('langKurdish') || 'Kurdish' },
        { code: 'ky', name: chrome.i18n.getMessage('langKyrgyz') || 'Kyrgyz' },
        { code: 'lo', name: chrome.i18n.getMessage('langLao') || 'Lao' },
        { code: 'la', name: chrome.i18n.getMessage('langLatin') || 'Latin' },
        { code: 'lv', name: chrome.i18n.getMessage('langLatvian') || 'Latvian' },
        { code: 'lt', name: chrome.i18n.getMessage('langLithuanian') || 'Lithuanian' },
        { code: 'lb', name: chrome.i18n.getMessage('langLuxembourgish') || 'Luxembourgish' },
        { code: 'mk', name: chrome.i18n.getMessage('langMacedonian') || 'Macedonian' },
        { code: 'mg', name: chrome.i18n.getMessage('langMalagasy') || 'Malagasy' },
        { code: 'ms', name: chrome.i18n.getMessage('langMalay') || 'Malay' },
        { code: 'ml', name: chrome.i18n.getMessage('langMalayalam') || 'Malayalam' },
        { code: 'mt', name: chrome.i18n.getMessage('langMaltese') || 'Maltese' },
        { code: 'mi', name: chrome.i18n.getMessage('langMaori') || 'Maori' },
        { code: 'mr', name: chrome.i18n.getMessage('langMarathi') || 'Marathi' },
        { code: 'mn', name: chrome.i18n.getMessage('langMongolian') || 'Mongolian' },
        { code: 'my', name: chrome.i18n.getMessage('langMyanmar') || 'Myanmar (Burmese)' },
        { code: 'ne', name: chrome.i18n.getMessage('langNepali') || 'Nepali' },
        { code: 'no', name: chrome.i18n.getMessage('langNorwegian') || 'Norwegian' },
        { code: 'ny', name: chrome.i18n.getMessage('langNyanja') || 'Nyanja (Chichewa)' },
        { code: 'or', name: chrome.i18n.getMessage('langOdia') || 'Odia (Oriya)' },
        { code: 'ps', name: chrome.i18n.getMessage('langPashto') || 'Pashto' },
        { code: 'fa', name: chrome.i18n.getMessage('langPersian') || 'Persian' },
        { code: 'pl', name: chrome.i18n.getMessage('langPolish') || 'Polish' },
        { code: 'pt', name: chrome.i18n.getMessage('langPortuguese') || 'Portuguese' },
        { code: 'pa', name: chrome.i18n.getMessage('langPunjabi') || 'Punjabi' },
        { code: 'ro', name: chrome.i18n.getMessage('langRomanian') || 'Romanian' },
        { code: 'ru', name: chrome.i18n.getMessage('langRussian') || 'Russian' },
        { code: 'sm', name: chrome.i18n.getMessage('langSamoan') || 'Samoan' },
        { code: 'gd', name: chrome.i18n.getMessage('langScotsGaelic') || 'Scots Gaelic' },
        { code: 'sr', name: chrome.i18n.getMessage('langSerbian') || 'Serbian' },
        { code: 'st', name: chrome.i18n.getMessage('langSesotho') || 'Sesotho' },
        { code: 'sn', name: chrome.i18n.getMessage('langShona') || 'Shona' },
        { code: 'sd', name: chrome.i18n.getMessage('langSindhi') || 'Sindhi' },
        { code: 'si', name: chrome.i18n.getMessage('langSinhala') || 'Sinhala (Sinhalese)' },
        { code: 'sk', name: chrome.i18n.getMessage('langSlovak') || 'Slovak' },
        { code: 'sl', name: chrome.i18n.getMessage('langSlovenian') || 'Slovenian' },
        { code: 'so', name: chrome.i18n.getMessage('langSomali') || 'Somali' },
        { code: 'es', name: chrome.i18n.getMessage('langSpanish') || 'Spanish' },
        { code: 'su', name: chrome.i18n.getMessage('langSundanese') || 'Sundanese' },
        { code: 'sw', name: chrome.i18n.getMessage('langSwahili') || 'Swahili' },
        { code: 'sv', name: chrome.i18n.getMessage('langSwedish') || 'Swedish' },
        { code: 'tl', name: chrome.i18n.getMessage('langTagalog') || 'Tagalog (Filipino)' },
        { code: 'tg', name: chrome.i18n.getMessage('langTajik') || 'Tajik' },
        { code: 'ta', name: chrome.i18n.getMessage('langTamil') || 'Tamil' },
        { code: 'tt', name: chrome.i18n.getMessage('langTatar') || 'Tatar' },
        { code: 'te', name: chrome.i18n.getMessage('langTelugu') || 'Telugu' },
        { code: 'th', name: chrome.i18n.getMessage('langThai') || 'Thai' },
        { code: 'tr', name: chrome.i18n.getMessage('langTurkish') || 'Turkish' },
        { code: 'tk', name: chrome.i18n.getMessage('langTurkmen') || 'Turkmen' },
        { code: 'uk', name: chrome.i18n.getMessage('langUkrainian') || 'Ukrainian' },
        { code: 'ur', name: chrome.i18n.getMessage('langUrdu') || 'Urdu' },
        { code: 'ug', name: chrome.i18n.getMessage('langUyghur') || 'Uyghur' },
        { code: 'uz', name: chrome.i18n.getMessage('langUzbek') || 'Uzbek' },
        { code: 'vi', name: chrome.i18n.getMessage('langVietnamese') || 'Vietnamese' },
        { code: 'cy', name: chrome.i18n.getMessage('langWelsh') || 'Welsh' },
        { code: 'xh', name: chrome.i18n.getMessage('langXhosa') || 'Xhosa' },
        { code: 'yi', name: chrome.i18n.getMessage('langYiddish') || 'Yiddish' },
        { code: 'yo', name: chrome.i18n.getMessage('langYoruba') || 'Yoruba' },
        { code: 'zu', name: chrome.i18n.getMessage('langZulu') || 'Zulu' }
    ];
}